name: Build and deploy to WordPress.org
on:
  release:
    types: [published]
jobs:
  tag:
    name: New release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Composer dependencies
        uses: php-actions/composer@v6
        with:
          dev: no
          php_version: 8.1
          php_extensions: bcmath

      - name: Install WP-CLI
        run: |
          curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
          chmod +x wp-cli.phar
          sudo mv wp-cli.phar /usr/local/bin/wp

#      - name: Set up Node.js
#        uses: actions/setup-node@v3
#        with:
#          node-version: '16'

#      - name: Set Execute Permissions for build_i18n.sh
#        run: chmod +x bin/build_i18n.sh

#      - name: Build assets and translation files
#        run: |
#          npm install
#          npm run build

      - name: WordPress Plugin Deploy
        id: deploy
        uses: 10up/action-wordpress-plugin-deploy@stable
        with:
          generate-zip: true
        env:
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SLUG: btcpay-givewp

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ steps.deploy.outputs.zip-path }}
          asset_name: btcpay-for-givewp.zip
          asset_content_type: application/zip
